@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.xenomustache.ironfurnaces.blocks;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;