@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.xenomustache.ironfurnaces.tileentity;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;